### ISSUE TITLE
[Question] Image Size and NVIDIA GPU Usage

### ISSUE THREAD

**Issue by orzanai** [steven-tel/CEN-HDR#1]
Hello Steven, I hope you are doing well!
First of all, I really liked your presentation on Sunday and the model that you proposed. So congrats and thank you for the contribution into this field! 

I'm working on Deep HDR and try to find a way to optimize HDR process into real time applications with maximum efficiency. I want to ask for capability of this model for different sized input images especially bigger ones such as more than 2000x2000 pixel. Do you think it is possible to get similar results? Moreover, if we try to achieve faster results with a card of the same scale as the NVIDIA 3090, do you think we faced any problem or have any advice?

Thanks in advance!

**Comment by steven-tel** [comment]
Hello Orzanai, thanks for your interest in our work.

There is no reasons it will not work using bigger images.
If you want to use your own dataset the easiest way  to apply knowledge distillation is to first train the teacher network on your data to see how it performes, you can use HDR-GAN as proposed in  our paper or use a more recently proposed network like [hdr-transformer](https://github.com/liuzhen03/HDR-Transformer-PyTorch). Then you can train cen-hdr directly using the prediction of the teacher model (not a composition of dataset gt and teacher prediction as label).

you should not face any problem  using the NVIDIA 3090 gpu.

if you are currently at Tel-aviv for ECCV, it would be a pleasure to meet to talk about afficient computational photography.

**Comment by orzanai** [comment]
Thank you so much for your fast response and detailed explanation! 
I would be delighted to meet you and learn more from you, but sadly I am not in Tel-Aviv. I look forward to your future work and hopefully meeting you someday. 
I will start working with your model as soon as possible; much appreciated.
